#%RAML 1.0
title: Person-data-PAPI

/employee-data-papi:
  /{name}:
    get:
      description:
      responses:
        200:
          body:
            application/json:
            
  post:
    description:
    body:
      application/json:
        

