#%RAML 1.0
title: assignment3

description: Create new API

/source:
  post:
    body:
      application/json:
        type: object
    responses:
      200:
        body:
          application/json:
            type : object
            properties:
              message:
                type: string
                example: "Working"
    